package com.lucerne.ui;

import com.lucerne.app.AppSession;
import com.lucerne.config.DatabaseConfig;
import com.lucerne.config.DatabaseConnection;
import com.lucerne.dao.QueryDAO;
import com.lucerne.ui.components.LoadingPane;
import com.lucerne.util.AlertUtil;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.DirectoryChooser;
import javafx.stage.FileChooser;
import java.io.File;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public final class DatabaseMaintenanceView extends StackPane {
    private final Label status=new Label("Not tested"),version=new Label("—"),response=new Label("—"),lastBackup=new Label("—");private final LoadingPane loading=new LoadingPane();
    public DatabaseMaintenanceView(){getChildren().addAll(build(),loading);test();loadLastBackup();}
    private VBox build(){VBox root=new VBox(18);root.setPadding(new Insets(24));Label title=new Label("Database Maintenance");title.getStyleClass().add("page-title");Label desc=new Label("Connection diagnostics and real command-line backup/restore. Operations report failure when MySQL tools are unavailable.");desc.getStyleClass().add("page-description");GridPane info=new GridPane();info.setHgap(18);info.setVgap(12);info.addRow(0,new Label("Database"),new Label(DatabaseConfig.databaseName()));info.addRow(1,new Label("Connection"),status);info.addRow(2,new Label("MySQL version"),version);info.addRow(3,new Label("Response time"),response);info.addRow(4,new Label("Last successful backup"),lastBackup);Button test=new Button("Test connection");test.setOnAction(e->test());Button backup=new Button("Create SQL backup");backup.getStyleClass().add("primary-button");backup.setOnAction(e->backup());Button restore=new Button("Restore SQL backup");restore.getStyleClass().add("danger-button");restore.setOnAction(e->restore());HBox actions=new HBox(10,test,backup,restore);VBox card=new VBox(18,info,new Separator(),actions);card.getStyleClass().add("content-card");card.setPadding(new Insets(20));root.getChildren().addAll(title,desc,card);return root;}
    private void test(){loading.show("Testing MySQL connection…");Task<DatabaseConnection.ConnectionStatus> t=new Task<>(){protected DatabaseConnection.ConnectionStatus call(){return DatabaseConnection.test();}};t.setOnSucceeded(e->{var r=t.getValue();status.setText(r.message());version.setText(r.version());response.setText(r.responseMillis()+" ms");loading.hide();});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void backup(){if(!AppSession.hasPermission("DATABASE_BACKUP")){AlertUtil.error("Not authorized","Your account cannot create backups.");return;}DirectoryChooser chooser=new DirectoryChooser();chooser.setTitle("Choose backup folder");File folder=chooser.showDialog(getScene().getWindow());if(folder==null)return;String name="lucerne_demo_"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"))+".sql";Path output=folder.toPath().resolve(name);loading.show("Running mysqldump…");Task<Integer> t=new Task<>(){protected Integer call()throws Exception{ProcessBuilder pb=new ProcessBuilder("mysqldump","-h",DatabaseConfig.host(),"-P",DatabaseConfig.port(),"-u",DatabaseConfig.username(),"--result-file="+output,DatabaseConfig.databaseName());pb.environment().put("MYSQL_PWD",DatabaseConfig.password());Process p=pb.start();return p.waitFor();}};t.setOnSucceeded(e->{loading.hide();if(t.getValue()==0){try{new QueryDAO().update("INSERT INTO backup_history(BackupPath,BackupType,Status,CreatedBy,StartedAt,CompletedAt) VALUES(?,'MANUAL','SUCCESS',?,NOW(),NOW())",List.of(output.toString(),AppSession.current().userId()));}catch(Exception ignored){}AlertUtil.info("Backup complete",output.toString());loadLastBackup();}else AlertUtil.error("Backup failed","mysqldump returned exit code "+t.getValue()+". Verify MySQL client tools and permissions.");});t.setOnFailed(e->{loading.hide();AlertUtil.error("Backup failed","mysqldump is not installed or could not be started.");});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void restore(){if(!AppSession.hasPermission("DATABASE_RESTORE")){AlertUtil.error("Not authorized","Your account cannot restore backups.");return;}FileChooser chooser=new FileChooser();chooser.setTitle("Select SQL backup");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("SQL files","*.sql"));File file=chooser.showOpenDialog(getScene().getWindow());if(file==null)return;if(!AlertUtil.confirm("Restore database","This will execute the selected SQL against "+DatabaseConfig.databaseName()+". Create a fresh backup first. Continue?"))return;loading.show("Restoring database…");Task<Integer> t=new Task<>(){protected Integer call()throws Exception{ProcessBuilder pb=new ProcessBuilder("mysql","-h",DatabaseConfig.host(),"-P",DatabaseConfig.port(),"-u",DatabaseConfig.username(),DatabaseConfig.databaseName());pb.environment().put("MYSQL_PWD",DatabaseConfig.password());pb.redirectInput(file);return pb.start().waitFor();}};t.setOnSucceeded(e->{loading.hide();if(t.getValue()==0)AlertUtil.info("Restore complete","The SQL file completed successfully. Restart the application.");else AlertUtil.error("Restore failed","mysql returned exit code "+t.getValue()+". The database may be partially changed; inspect the backup and server logs.");});t.setOnFailed(e->{loading.hide();AlertUtil.error("Restore failed","The MySQL client could not be started.");});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void loadLastBackup(){Task<Object> t=new Task<>(){protected Object call()throws Exception{return new QueryDAO().scalar("SELECT MAX(CompletedAt) FROM backup_history WHERE Status='SUCCESS'",List.of());}};t.setOnSucceeded(e->lastBackup.setText(t.getValue()==null?"No successful backup recorded":String.valueOf(t.getValue())));Thread x=new Thread(t);x.setDaemon(true);x.start();}
}
