package com.lucerne.ui;

import com.lucerne.dao.DiscountDAO;
import com.lucerne.ui.components.LoadingPane;
import com.lucerne.ui.components.MetricCard;
import com.lucerne.util.AlertUtil;
import com.lucerne.util.ExportUtil;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class DiscountsView extends StackPane {
    private final DiscountDAO dao=new DiscountDAO();private final TableView<Map<String,Object>> table=new TableView<>();private final TextField search=new TextField();private final ComboBox<String> state=new ComboBox<>();private final DatePicker from=new DatePicker(),to=new DatePicker();private final Label count=new Label();private final LoadingPane loading=new LoadingPane();private final MetricCard total=new MetricCard("Total discounts"),current=new MetricCard("Current promotions"),inactive=new MetricCard("Inactive / expired");private List<Map<String,Object>> rows=List.of();private List<String> columns=List.of();
    public DiscountsView(){getChildren().addAll(build(),loading);load();}
    private VBox build(){VBox root=new VBox(18);root.setPadding(new Insets(24));root.getStyleClass().add("page-root");Label title=new Label("Discounts");title.getStyleClass().add("page-title");Label description=new Label("Create percentage or fixed promotions, date limits, minimum purchases and maximum discount caps.");description.getStyleClass().add("page-description");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);Button add=new Button("Add discount");add.getStyleClass().add("primary-button");add.setOnAction(e->form(null));Button edit=new Button("Edit");edit.setOnAction(e->{Map<String,Object> row=selected();if(row!=null)form(row);});Button toggle=new Button("Activate / deactivate");toggle.setOnAction(e->toggle());Button export=new Button("Export filtered");export.setOnAction(e->export());Button refresh=new Button("Refresh");refresh.setOnAction(e->load());HBox heading=new HBox(10,new VBox(4,title,description),spacer,add,edit,toggle,export,refresh);heading.setAlignment(Pos.CENTER_LEFT);
        HBox cards=new HBox(14,total,current,inactive);for(MetricCard card:List.of(total,current,inactive)){card.setMaxWidth(Double.MAX_VALUE);HBox.setHgrow(card,Priority.ALWAYS);}FlowPane filters=new FlowPane(10,10);filters.getStyleClass().add("filter-panel");filters.setPadding(new Insets(14));search.setPromptText("Code or description");search.setPrefWidth(240);state.getItems().addAll("ALL","CURRENT","ACTIVE","INACTIVE","EXPIRED");state.setValue("ALL");from.setPromptText("Valid from");to.setPromptText("Valid to");Button apply=new Button("Apply filters");apply.getStyleClass().add("primary-button");apply.setOnAction(e->load());Button clear=new Button("Clear");clear.setOnAction(e->{search.clear();state.setValue("ALL");from.setValue(null);to.setValue(null);load();});filters.getChildren().addAll(search,state,from,to,apply,clear);search.setOnAction(e->load());table.setPlaceholder(new Label("No discounts match the filters."));table.setRowFactory(v->{TableRow<Map<String,Object>> row=new TableRow<>();row.setOnMouseClicked(e->{if(e.getClickCount()==2&&!row.isEmpty())form(row.getItem());});return row;});VBox card=new VBox(10,count,table);card.getStyleClass().add("content-card");card.setPadding(new Insets(14));VBox.setVgrow(table,Priority.ALWAYS);root.getChildren().addAll(heading,cards,filters,card);VBox.setVgrow(card,Priority.ALWAYS);return root;}
    private void load(){if(from.getValue()!=null&&to.getValue()!=null&&from.getValue().isAfter(to.getValue())){AlertUtil.warning("Invalid dates","The first date cannot be after the second date.");return;}loading.show("Loading discounts…");Task<List<Map<String,Object>>> task=new Task<>(){protected List<Map<String,Object>> call()throws Exception{return dao.search(search.getText(),state.getValue(),from.getValue(),to.getValue());}};task.setOnSucceeded(e->{loading.hide();render(task.getValue());});task.setOnFailed(e->{loading.hide();AlertUtil.error("Discounts unavailable","The discount query could not be completed.");});start(task,"discount-load");}
    private void render(List<Map<String,Object>> result){rows=result;table.getColumns().clear();columns=rows.isEmpty()?List.of("Discount ID","Code","Description","Percentage","Fixed Amount","Minimum Purchase","Maximum Discount","Start Date","End Date","Active","Status"):new ArrayList<>(rows.getFirst().keySet());for(String column:columns){TableColumn<Map<String,Object>,Object> c=new TableColumn<>(column);c.setCellValueFactory(v->new ReadOnlyObjectWrapper<>(v.getValue().get(column)));c.setPrefWidth(Math.max(105,Math.min(210,column.length()*12.0)));table.getColumns().add(c);}table.getItems().setAll(rows);count.setText(rows.size()+" matching discounts");long currentCount=rows.stream().filter(r->"CURRENT".equals(String.valueOf(r.get("Status")))).count();long inactiveCount=rows.size()-currentCount;total.setValue(String.valueOf(rows.size()));current.setValue(String.valueOf(currentCount));inactive.setValue(String.valueOf(inactiveCount));}
    private Map<String,Object> selected(){Map<String,Object> row=table.getSelectionModel().getSelectedItem();if(row==null)AlertUtil.warning("Select a discount","Choose a discount row first.");return row;}
    private void form(Map<String,Object> row){Dialog<DiscountDAO.DiscountForm> dialog=new Dialog<>();dialog.setTitle(row==null?"Add discount":"Edit discount");dialog.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);TextField code=text(row,"Code"),description=text(row,"Description"),percentage=text(row,"Percentage"),fixed=text(row,"Fixed Amount"),minimum=text(row,"Minimum Purchase"),maximum=text(row,"Maximum Discount");DatePicker start=new DatePicker(date(row,"Start Date",LocalDate.now())),end=new DatePicker(date(row,"End Date",LocalDate.now().plusMonths(1)));GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(10);grid.setPadding(new Insets(18));grid.addRow(0,new Label("Code*"),code);grid.addRow(1,new Label("Description"),description);grid.addRow(2,new Label("Percentage"),percentage);grid.addRow(3,new Label("Fixed amount"),fixed);grid.addRow(4,new Label("Minimum purchase"),minimum);grid.addRow(5,new Label("Maximum discount"),maximum);grid.addRow(6,new Label("Start date*"),start);grid.addRow(7,new Label("End date*"),end);dialog.getDialogPane().setContent(grid);dialog.setResultConverter(button->{if(button!=ButtonType.OK)return null;try{String clean=code.getText().trim().toUpperCase();BigDecimal pct=money(percentage.getText(),false),fix=money(fixed.getText(),false),min=money(minimum.getText(),false),max=money(maximum.getText(),true);if(clean.isBlank()||start.getValue()==null||end.getValue()==null||start.getValue().isAfter(end.getValue())||pct.compareTo(BigDecimal.valueOf(100))>0||(pct.signum()==0&&fix.signum()==0))throw new IllegalArgumentException();return new DiscountDAO.DiscountForm(clean,description.getText().trim(),pct,fix,min,max,start.getValue(),end.getValue());}catch(Exception exception){AlertUtil.warning("Invalid discount","Use valid dates and non-negative values; percentage must be 0–100 and either percentage or fixed amount must be positive.");return null;}});dialog.showAndWait().ifPresent(form->save(row,form));}
    private void save(Map<String,Object> row,DiscountDAO.DiscountForm form){Integer id=row==null?null:((Number)row.get("Discount ID")).intValue();loading.show("Saving discount…");Task<Void> task=new Task<>(){protected Void call()throws Exception{dao.save(id,form);return null;}};task.setOnSucceeded(e->{loading.hide();AlertUtil.info("Discount saved",form.code()+" is ready for its configured dates.");load();});task.setOnFailed(e->{loading.hide();AlertUtil.error("Discount not saved","Check that the code is unique and the values satisfy database rules.");});start(task,"discount-save");}
    private void toggle(){Map<String,Object> row=selected();if(row==null)return;boolean active=row.get("Active") instanceof Boolean b?b:((Number)row.get("Active")).intValue()!=0;if(!AlertUtil.confirm(active?"Deactivate discount":"Activate discount","Continue with "+row.get("Code")+"?"))return;Task<Void> task=new Task<>(){protected Void call()throws Exception{dao.setActive(((Number)row.get("Discount ID")).intValue(),!active);return null;}};task.setOnSucceeded(e->{AlertUtil.info("Discount updated","The active state was changed.");load();});task.setOnFailed(e->AlertUtil.error("Update failed","The discount state was not changed."));start(task,"discount-toggle");}
    private void export(){if(rows.isEmpty()){AlertUtil.warning("Nothing to export","No discounts match the current filters.");return;}Path path=ExportUtil.chooseCsv(getScene().getWindow(),"discounts-filtered.csv");if(path==null)return;try{ExportUtil.writeCsv(path,columns,rows);AlertUtil.info("Export complete",path.toString());}catch(Exception e){AlertUtil.error("Export failed","The CSV file could not be written.");}}
    private TextField text(Map<String,Object> row,String key){Object value=row==null?null:row.get(key);return new TextField(value==null?"":String.valueOf(value));}private LocalDate date(Map<String,Object> row,String key,LocalDate fallback){Object value=row==null?null:row.get(key);if(value instanceof java.sql.Date d)return d.toLocalDate();if(value instanceof LocalDate d)return d;return fallback;}private BigDecimal money(String value,boolean nullable){if(value==null||value.isBlank())return nullable?null:BigDecimal.ZERO;BigDecimal result=new BigDecimal(value.trim());if(result.signum()<0)throw new IllegalArgumentException();return result;}private static void start(Task<?> task,String name){Thread thread=new Thread(task,name);thread.setDaemon(true);thread.start();}
}
