package com.lucerne.ui;

import com.lucerne.app.AppSession;
import com.lucerne.config.ApplicationConfig;
import com.lucerne.dao.InventoryDAO;
import com.lucerne.dao.QueryDAO;
import com.lucerne.model.Role;
import com.lucerne.ui.components.LoadingPane;
import com.lucerne.ui.components.MetricCard;
import com.lucerne.util.AlertUtil;
import com.lucerne.util.ExportUtil;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/** Inventory overview and atomic adjustment/transfer workflows. */
public final class InventoryView extends StackPane {
    private final InventoryDAO dao=new InventoryDAO();
    private final TableView<Map<String,Object>> table=new TableView<>();
    private final TextField search=new TextField();
    private final ComboBox<String> locationType=new ComboBox<>();
    private final ComboBox<QueryDAO.Option> location=new ComboBox<>();
    private final ComboBox<QueryDAO.Option> category=new ComboBox<>();
    private final ComboBox<String> stockStatus=new ComboBox<>();
    private final TextField minimumQuantity=new TextField(),maximumQuantity=new TextField();
    private final DatePicker updatedFrom=new DatePicker(),updatedTo=new DatePicker();
    private final ComboBox<Integer> pageSize=new ComboBox<>();
    private final Label matching=new Label("0 matching inventory rows"),pageLabel=new Label("Page 1");
    private final Button previous=new Button("Previous"),next=new Button("Next");
    private final LoadingPane loading=new LoadingPane();
    private final MetricCard quantity=metric("Total quantity"),cost=metric("Inventory cost"),retail=metric("Retail value"),low=metric("Low stock"),out=metric("Out of stock"),over=metric("Overstock");
    private final BarChart<String,Number> chart=new BarChart<>(new CategoryAxis(),new NumberAxis());
    private List<Map<String,Object>> rows=List.of();private List<String> columns=List.of();private int totalRows,page;

    public InventoryView(){getChildren().addAll(build(),loading);loadLookups();load();}
    private Node build(){
        VBox root=new VBox(18);root.setPadding(new Insets(24));root.getStyleClass().add("page-root");
        Label title=new Label("Inventory");title.getStyleClass().add("page-title");Label desc=new Label("Branch and warehouse stock, valuation, movement history and safe transactional operations.");desc.getStyleClass().add("page-description");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);
        Button adjust=new Button("Adjust quantity");adjust.getStyleClass().add("primary-button");adjust.setOnAction(e->adjust());Button transfer=new Button("Transfer stock");transfer.setOnAction(e->transfer());Button damaged=new Button("Mark damaged");damaged.setOnAction(e->damaged());Button history=new Button("Movement history");history.setOnAction(e->history());boolean manage=AppSession.hasPermission("MANAGE_INVENTORY");adjust.setVisible(manage);adjust.setManaged(manage);transfer.setVisible(manage);transfer.setManaged(manage);damaged.setVisible(manage);damaged.setManaged(manage);Button export=new Button("Export filtered");export.setOnAction(e->export());Button refresh=new Button("Refresh");refresh.setOnAction(e->load());HBox heading=new HBox(10,new VBox(4,title,desc),spacer,adjust,transfer,damaged,history,export,refresh);heading.setAlignment(Pos.CENTER_LEFT);
        FlowPane cards=new FlowPane(12,12,quantity,cost,retail,low,out,over);for(Node n:cards.getChildren())if(n instanceof MetricCard m)m.setPrefWidth(190);
        FlowPane filters=new FlowPane(10,10);filters.getStyleClass().add("filter-panel");filters.setPadding(new Insets(14));search.setPromptText("Product, SKU, size or color");search.setPrefWidth(240);search.setOnAction(e->{page=0;load();});locationType.getItems().addAll("All locations","BRANCH","WAREHOUSE");locationType.setValue("All locations");locationType.setOnAction(e->populateLocations());location.setPromptText("All locations");category.setPromptText("All categories");stockStatus.getItems().addAll("All stock states","IN_STOCK","LOW_STOCK","OUT_OF_STOCK","OVERSTOCK");stockStatus.setValue("All stock states");minimumQuantity.setPromptText("Min qty");maximumQuantity.setPromptText("Max qty");updatedFrom.setPromptText("Updated from");updatedTo.setPromptText("Updated to");pageSize.getItems().addAll(10,25,50,100);pageSize.setValue(ApplicationConfig.DEFAULT_PAGE_SIZE);Button apply=new Button("Apply filters");apply.getStyleClass().add("primary-button");apply.setOnAction(e->{page=0;load();});Button clear=new Button("Clear");clear.setOnAction(e->clear());filters.getChildren().addAll(search,locationType,location,category,stockStatus,minimumQuantity,maximumQuantity,updatedFrom,updatedTo,new Label("Rows"),pageSize,apply,clear);
        table.setPlaceholder(new Label("No stock rows match these filters."));table.setColumnResizePolicy(TableView.UNCONSTRAINED_RESIZE_POLICY);table.setRowFactory(v->{TableRow<Map<String,Object>> row=new TableRow<>();row.setOnMouseClicked(e->{if(e.getClickCount()==2&&!row.isEmpty())history();});return row;});VBox tableCard=new VBox(10,matching,table);tableCard.getStyleClass().add("content-card");tableCard.setPadding(new Insets(14));VBox.setVgrow(table,Priority.ALWAYS);
        chart.setTitle("Stock quantity by category");chart.setLegendVisible(false);chart.setAnimated(false);chart.getXAxis().setLabel("Category");chart.getYAxis().setLabel("Units");chart.setPrefHeight(290);VBox chartCard=new VBox(chart);chartCard.getStyleClass().add("content-card");chartCard.setPadding(new Insets(12));chartCard.setPrefWidth(430);HBox center=new HBox(16,tableCard,chartCard);HBox.setHgrow(tableCard,Priority.ALWAYS);VBox.setVgrow(center,Priority.ALWAYS);
        previous.setOnAction(e->{if(page>0){page--;load();}});next.setOnAction(e->{if((page+1)*pageSize.getValue()<totalRows){page++;load();}});Region pageSpacer=new Region();HBox.setHgrow(pageSpacer,Priority.ALWAYS);HBox paging=new HBox(10,matching,pageSpacer,previous,pageLabel,next);paging.setAlignment(Pos.CENTER_LEFT);
        root.getChildren().addAll(heading,cards,filters,center,paging);VBox.setVgrow(center,Priority.ALWAYS);return root;
    }
    private static MetricCard metric(String title){MetricCard m=new MetricCard(title);m.setValue("—");return m;}
    private void loadLookups(){Task<Lookups> t=new Task<>(){protected Lookups call()throws Exception{return new Lookups(dao.branches(),dao.warehouses(),dao.categories());}};t.setOnSucceeded(e->{setOptions(category,"All categories",t.getValue().categories());populateLocations(t.getValue());});t.setOnFailed(e->AlertUtil.error("Inventory filters unavailable","Locations and categories could not be loaded."));start(t,"inventory-lookups");}
    private Lookups cachedLookups;
    private void populateLocations(Lookups data){cachedLookups=data;populateLocations();}
    private void populateLocations(){if(cachedLookups==null)return;location.getItems().clear();location.getItems().add(new QueryDAO.Option(null,"All locations"));String type=locationType.getValue();if("BRANCH".equals(type))location.getItems().addAll(cachedLookups.branches());else if("WAREHOUSE".equals(type))location.getItems().addAll(cachedLookups.warehouses());else{for(QueryDAO.Option o:cachedLookups.branches())location.getItems().add(new QueryDAO.Option("B:"+o.id(),"Branch · "+o.label()));for(QueryDAO.Option o:cachedLookups.warehouses())location.getItems().add(new QueryDAO.Option("W:"+o.id(),"Warehouse · "+o.label()));}location.getSelectionModel().selectFirst();}
    private static void setOptions(ComboBox<QueryDAO.Option> box,String all,List<QueryDAO.Option> values){box.getItems().setAll(new QueryDAO.Option(null,all));box.getItems().addAll(values);box.getSelectionModel().selectFirst();}
    private void load(){InventoryDAO.InventoryFilter filter;try{filter=filter();}catch(IllegalArgumentException e){AlertUtil.warning("Invalid filters",e.getMessage());return;}loading.show("Loading inventory and valuations…");Task<PageData> task=new Task<>(){protected PageData call()throws Exception{return new PageData(dao.search(filter,pageSize.getValue(),page*pageSize.getValue()),dao.summary(filter),dao.categorySummary(filter));}};task.setOnSucceeded(e->{render(task.getValue());loading.hide();});task.setOnFailed(e->{loading.hide();AlertUtil.error("Inventory unavailable","The inventory query failed. Verify the final database view and MySQL connection.");});start(task,"inventory-load");}
    private InventoryDAO.InventoryFilter filter(){if(updatedFrom.getValue()!=null&&updatedTo.getValue()!=null&&updatedFrom.getValue().isAfter(updatedTo.getValue()))throw new IllegalArgumentException("Updated-from cannot be after updated-to.");Integer min=parseOptionalInt(minimumQuantity.getText()),max=parseOptionalInt(maximumQuantity.getText());if(min!=null&&max!=null&&min>max)throw new IllegalArgumentException("Minimum quantity cannot exceed maximum quantity.");String type="All locations".equals(locationType.getValue())?null:locationType.getValue();Integer id=null;if(location.getValue()!=null&&location.getValue().id()!=null){Object raw=location.getValue().id();if(raw instanceof Number n)id=n.intValue();else{String v=raw.toString();type=v.startsWith("B:")?"BRANCH":"WAREHOUSE";id=Integer.parseInt(v.substring(2));}}return new InventoryDAO.InventoryFilter(search.getText(),type,id,optionLabel(category),"All stock states".equals(stockStatus.getValue())?null:stockStatus.getValue(),min,max,updatedFrom.getValue(),updatedTo.getValue());}
    private void render(PageData d){rows=d.result().rows();columns=d.result().columns();totalRows=d.result().total();table.getColumns().clear();for(String col:columns){if((col.equals("Branch ID")||col.equals("Warehouse ID")||col.equals("Variant ID")||col.equals("Product ID")))continue;TableColumn<Map<String,Object>,Object> c=new TableColumn<>(col);c.setCellValueFactory(v->new ReadOnlyObjectWrapper<>(v.getValue().get(col)));c.setPrefWidth(Math.max(105,Math.min(210,col.length()*12)));c.setCellFactory(v->new TableCell<>(){protected void updateItem(Object item,boolean empty){super.updateItem(item,empty);setText(empty||item==null?null:format(item));if(!empty&&col.equals("Stock Status"))getStyleClass().add("status-cell");}});table.getColumns().add(c);}table.getItems().setAll(rows);matching.setText(totalRows+" matching inventory rows");InventoryDAO.Summary s=d.summary();quantity.setValue(String.format("%,d",s.quantity()));cost.setValue(String.format("%,.2f",s.costValue()));retail.setValue(String.format("%,.2f",s.retailValue()));low.setValue(String.valueOf(s.lowStock()));out.setValue(String.valueOf(s.outOfStock()));over.setValue(String.valueOf(s.overstock()));quantity.setSubtitle("Units on hand");cost.setSubtitle("Cost-price valuation");retail.setSubtitle("Selling-price valuation");low.setSubtitle("At or below reorder");out.setSubtitle("Zero quantity");over.setSubtitle("Eight times reorder or more");chart.getData().clear();XYChart.Series<String,Number> series=new XYChart.Series<>();for(Map<String,Object> row:d.categories())series.getData().add(new XYChart.Data<>(String.valueOf(row.get("Category")),((Number)row.get("Quantity")).doubleValue()));chart.getData().add(series);int pages=Math.max(1,(int)Math.ceil(totalRows/(double)pageSize.getValue()));pageLabel.setText("Page "+(page+1)+" of "+pages);previous.setDisable(page==0);next.setDisable((page+1)*pageSize.getValue()>=totalRows);}
    private void adjust(){Map<String,Object> row=selected();if(row==null)return;Dialog<InventoryDAO.StockOperation> d=operationDialog("Adjust quantity","Enter a positive number to add stock or a negative number to remove stock.",row,true);d.showAndWait().ifPresent(op->run("Adjusting inventory…",()->dao.adjust(op),"Inventory quantity adjusted."));}
    private void damaged(){Map<String,Object> row=selected();if(row==null)return;Dialog<InventoryDAO.StockOperation> d=operationDialog("Mark damaged stock","The quantity is removed from available stock and recorded permanently.",row,false);d.showAndWait().ifPresent(op->run("Recording damaged stock…",()->dao.markDamaged(op),"Damaged stock recorded."));}
    private Dialog<InventoryDAO.StockOperation> operationDialog(String title,String header,Map<String,Object> row,boolean allowNegative){Dialog<InventoryDAO.StockOperation> d=new Dialog<>();d.setTitle(title);d.setHeaderText(header);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);TextField qty=new TextField();qty.setPromptText(allowNegative?"Example: 5 or -2":"Positive quantity");TextArea reason=new TextArea();reason.setPromptText("Reason *");reason.setPrefRowCount(3);GridPane g=new GridPane();g.setHgap(12);g.setVgap(10);g.setPadding(new Insets(18));g.addRow(0,new Label("Product"),new Label(String.valueOf(row.get("Product"))));g.addRow(1,new Label("Location"),new Label(row.get("Location Type")+" · "+row.get("Location")));g.addRow(2,new Label("Quantity *"),qty);g.addRow(3,new Label("Reason *"),reason);d.getDialogPane().setContent(g);d.setResultConverter(b->{if(b!=ButtonType.OK)return null;try{int q=Integer.parseInt(qty.getText().trim());if(!allowNegative&&q<=0)throw new NumberFormatException();if(reason.getText().isBlank())throw new IllegalArgumentException("Reason is required.");return new InventoryDAO.StockOperation(String.valueOf(row.get("Location Type")),locationId(row),variantId(row),q,reason.getText().trim());}catch(NumberFormatException e){AlertUtil.warning("Invalid quantity",allowNegative?"Enter a non-zero whole number.":"Enter a positive whole number.");return null;}catch(IllegalArgumentException e){AlertUtil.warning("Missing reason",e.getMessage());return null;}});return d;}
    private void transfer(){Map<String,Object> row=selected();if(row==null||cachedLookups==null)return;Dialog<InventoryDAO.TransferOperation> d=new Dialog<>();d.setTitle("Transfer stock");d.setHeaderText("Source stock is locked, validated and moved in one database transaction.");d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);ComboBox<String> toType=new ComboBox<>();toType.getItems().addAll("BRANCH","WAREHOUSE");toType.setValue("BRANCH");ComboBox<QueryDAO.Option> toLocation=new ComboBox<>();Runnable fill=()->{toLocation.getItems().setAll(toType.getValue().equals("BRANCH")?cachedLookups.branches():cachedLookups.warehouses());if(!toLocation.getItems().isEmpty())toLocation.getSelectionModel().selectFirst();};toType.setOnAction(e->fill.run());fill.run();TextField q=new TextField();TextArea reason=new TextArea();reason.setPrefRowCount(3);GridPane g=new GridPane();g.setHgap(12);g.setVgap(10);g.setPadding(new Insets(18));g.addRow(0,new Label("Source"),new Label(row.get("Location Type")+" · "+row.get("Location")));g.addRow(1,new Label("Destination type"),toType);g.addRow(2,new Label("Destination"),toLocation);g.addRow(3,new Label("Quantity *"),q);g.addRow(4,new Label("Reason"),reason);d.getDialogPane().setContent(g);d.setResultConverter(b->{if(b!=ButtonType.OK)return null;try{int qty=Integer.parseInt(q.getText().trim());if(qty<=0||toLocation.getValue()==null)throw new IllegalArgumentException();return new InventoryDAO.TransferOperation(String.valueOf(row.get("Location Type")),locationId(row),toType.getValue(),((Number)toLocation.getValue().id()).intValue(),variantId(row),qty,reason.getText().trim());}catch(Exception e){AlertUtil.warning("Invalid transfer","Choose a destination and enter a positive whole-number quantity.");return null;}});d.showAndWait().ifPresent(op->run("Transferring stock…",()->dao.transfer(op),"Stock transfer completed."));}
    private void history(){Map<String,Object> row=selected();if(row==null)return;loading.show("Loading movement history…");Task<List<Map<String,Object>>> t=new Task<>(){protected List<Map<String,Object>> call()throws Exception{return dao.movementHistory(variantId(row));}};t.setOnSucceeded(e->{loading.hide();showHistory(row,t.getValue());});t.setOnFailed(e->{loading.hide();AlertUtil.error("History unavailable","Stock movements could not be loaded.");});start(t,"movement-history");}
    private void showHistory(Map<String,Object> row,List<Map<String,Object>> data){Dialog<Void> d=new Dialog<>();d.setTitle("Stock movement history");d.setHeaderText(row.get("Product")+" · "+row.get("Color")+" · "+row.get("Size"));d.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);TableView<Map<String,Object>> t=new TableView<>();if(!data.isEmpty())for(String col:data.getFirst().keySet()){TableColumn<Map<String,Object>,Object> c=new TableColumn<>(col);c.setCellValueFactory(v->new ReadOnlyObjectWrapper<>(v.getValue().get(col)));c.setPrefWidth(130);t.getColumns().add(c);}t.getItems().setAll(data);t.setPlaceholder(new Label("No movements were recorded for this variant."));t.setPrefSize(850,500);d.getDialogPane().setContent(t);d.showAndWait();}
    private Map<String,Object> selected(){Map<String,Object> row=table.getSelectionModel().getSelectedItem();if(row==null)AlertUtil.warning("Select inventory","Choose an inventory row first.");return row;}
    private static int variantId(Map<String,Object> r){return ((Number)r.get("Variant ID")).intValue();}private static int locationId(Map<String,Object> r){Object v="BRANCH".equals(r.get("Location Type"))?r.get("Branch ID"):r.get("Warehouse ID");return ((Number)v).intValue();}
    private void run(String message,SqlRunnable action,String success){loading.show(message);Task<Void> t=new Task<>(){protected Void call()throws Exception{action.run();return null;}};t.setOnSucceeded(e->{loading.hide();AlertUtil.info("Completed",success);load();});t.setOnFailed(e->{loading.hide();AlertUtil.error("Operation rolled back",t.getException()==null?"The stock operation failed.":t.getException().getMessage());});start(t,"inventory-operation");}
    private void export(){if(rows.isEmpty()){AlertUtil.warning("Nothing to export","No inventory rows are visible.");return;}Path path=ExportUtil.chooseCsv(getScene().getWindow(),"inventory-filtered.csv");if(path==null)return;List<String> safe=columns.stream().filter(c->!c.endsWith(" ID")).toList();try{ExportUtil.writeCsv(path,safe,rows);AlertUtil.info("Export complete","Filtered inventory was exported.");}catch(Exception e){AlertUtil.error("Export failed","The CSV file could not be written.");}}
    private void clear(){search.clear();locationType.setValue("All locations");populateLocations();if(!category.getItems().isEmpty())category.getSelectionModel().selectFirst();stockStatus.setValue("All stock states");minimumQuantity.clear();maximumQuantity.clear();updatedFrom.setValue(null);updatedTo.setValue(null);page=0;load();}
    private static Integer parseOptionalInt(String raw){if(raw==null||raw.isBlank())return null;try{int v=Integer.parseInt(raw.trim());if(v<0)throw new NumberFormatException();return v;}catch(NumberFormatException e){throw new IllegalArgumentException("Quantity filters must be non-negative whole numbers.");}}
    private static String optionLabel(ComboBox<QueryDAO.Option> b){return b.getValue()==null||b.getValue().id()==null?null:b.getValue().label();}
    private static String format(Object v){if(v instanceof BigDecimal b)return String.format("%,.2f",b);return String.valueOf(v);}
    private static void start(Task<?> t,String name){Thread x=new Thread(t,name);x.setDaemon(true);x.start();}
    @FunctionalInterface private interface SqlRunnable{void run()throws Exception;}
    private record Lookups(List<QueryDAO.Option> branches,List<QueryDAO.Option> warehouses,List<QueryDAO.Option> categories){}
    private record PageData(QueryDAO.QueryResult result,InventoryDAO.Summary summary,List<Map<String,Object>> categories){}
}
