package com.lucerne.ui;

import com.lucerne.app.AppSession;
import com.lucerne.app.NavigationManager;
import com.lucerne.config.ApplicationConfig;
import com.lucerne.config.DatabaseConnection;
import com.lucerne.dao.QueryDAO;
import com.lucerne.service.AuthenticationService;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.util.Duration;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;

public final class MainLayout extends BorderPane {
    private final AuthenticationService authenticationService;private final Runnable onLogout;private final VBox sidebar=new VBox();private final StackPane content=new StackPane();private final Label pageTitle=new Label("Dashboard");private final Label breadcrumb=new Label("Home / Dashboard");private final Label dbStatus=new Label("Checking database…");private final Label lastRefresh=new Label("Ready");private final Button notificationButton=new Button("Notifications");private final Map<String,Button> navButtons=new HashMap<>();private Timeline sessionTimeline;private boolean collapsed=false;
    public MainLayout(AuthenticationService service,Runnable onLogout){this.authenticationService=service;this.onLogout=onLogout;getStyleClass().add("app-shell");setLeft(buildSidebar());setTop(buildTopbar());setCenter(content);setBottom(buildStatusbar());open("dashboard","Dashboard");startClock();testDatabase();loadNotificationCount();}
    private Node buildSidebar(){sidebar.getStyleClass().add("sidebar");sidebar.setPrefWidth(255);sidebar.setMinWidth(255);Label brand=new Label("LUCERNE");brand.getStyleClass().add("sidebar-brand");Label subtitle=new Label("Boutique Management");subtitle.getStyleClass().add("sidebar-subtitle");Button collapse=new Button("☰");collapse.getStyleClass().add("sidebar-collapse");collapse.setOnAction(e->toggleSidebar());HBox brandRow=new HBox(10,new VBox(2,brand,subtitle),new Region(),collapse);HBox.setHgrow(brandRow.getChildren().get(1),Priority.ALWAYS);brandRow.setAlignment(Pos.CENTER_LEFT);brandRow.setPadding(new Insets(22,16,18,18));sidebar.getChildren().add(brandRow);ScrollPane scroll=new ScrollPane();scroll.setFitToWidth(true);scroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);scroll.getStyleClass().add("sidebar-scroll");VBox groups=new VBox(12);groups.setPadding(new Insets(4,10,12,10));for(var group:NavigationManager.forRole(AppSession.current().role())){Label groupTitle=new Label(group.title().toUpperCase());groupTitle.getStyleClass().add("nav-group-title");VBox box=new VBox(4,groupTitle);for(var item:group.items()){Button button=new Button(item.icon()+"   "+item.label());button.getStyleClass().add("nav-button");button.setMaxWidth(Double.MAX_VALUE);button.setAlignment(Pos.CENTER_LEFT);button.setUserData(item);button.setOnAction(e->open(item.key(),item.label()));navButtons.put(item.key(),button);box.getChildren().add(button);}groups.getChildren().add(box);}scroll.setContent(groups);VBox.setVgrow(scroll,Priority.ALWAYS);Label user=new Label(AppSession.current().fullName());user.getStyleClass().add("sidebar-user");Label role=new Label(AppSession.current().role().name());role.getStyleClass().add("role-badge");Button logout=new Button("Sign out");logout.getStyleClass().add("logout-button");logout.setMaxWidth(Double.MAX_VALUE);logout.setOnAction(e->logout());VBox footer=new VBox(6,user,role,logout);footer.setPadding(new Insets(14));sidebar.getChildren().addAll(scroll,footer);return sidebar;}
    private Node buildTopbar(){BorderPane bar=new BorderPane();bar.getStyleClass().add("topbar");bar.setPadding(new Insets(14,22,14,22));pageTitle.getStyleClass().add("topbar-title");breadcrumb.getStyleClass().add("breadcrumb");bar.setLeft(new VBox(2,pageTitle,breadcrumb));Label date=new Label(LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE, dd MMM yyyy")));date.getStyleClass().add("topbar-date");notificationButton.getStyleClass().add("notification-button");notificationButton.setOnAction(e->open("notifications","Notifications"));MenuItem profileItem=new MenuItem("Profile");profileItem.setOnAction(e->open("profile","Profile"));MenuItem settingsItem=new MenuItem("Settings");settingsItem.setOnAction(e->open("settings",AppSession.hasPermission("MANAGE_SETTINGS")?"System Settings":"Profile"));MenuItem logoutItem=new MenuItem("Sign out");logoutItem.setOnAction(e->logout());MenuButton userMenu=new MenuButton(AppSession.current().fullName());userMenu.getItems().add(profileItem);userMenu.getItems().add(settingsItem);userMenu.getItems().add(new SeparatorMenuItem());userMenu.getItems().add(logoutItem);userMenu.getStyleClass().add("profile-menu");HBox right=new HBox(14,notificationButton,new Separator(javafx.geometry.Orientation.VERTICAL),date,userMenu);right.setAlignment(Pos.CENTER_RIGHT);bar.setRight(right);return bar;}
    private Node buildStatusbar(){HBox bar=new HBox(16);bar.getStyleClass().add("statusbar");bar.setPadding(new Insets(7,16,7,16));Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);bar.getChildren().addAll(dbStatus,new Label("User: "+AppSession.current().username()),spacer,lastRefresh,new Label("v"+ApplicationConfig.VERSION));return bar;}
    private void logout(){if(sessionTimeline!=null)sessionTimeline.stop();authenticationService.logout(AppSession.current());AppSession.clear();onLogout.run();}
    private void open(String key,String label){content.getChildren().setAll(PageFactory.create(key));pageTitle.setText(label);breadcrumb.setText("Home / "+label);lastRefresh.setText("Opened "+LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));navButtons.values().forEach(b->b.getStyleClass().remove("nav-button-selected"));Button selected=navButtons.get(key);if(selected!=null)selected.getStyleClass().add("nav-button-selected");}
    private void toggleSidebar(){collapsed=!collapsed;sidebar.setPrefWidth(collapsed?78:255);sidebar.setMinWidth(collapsed?78:255);for(Button button:navButtons.values()){var item=(NavigationManager.NavItem)button.getUserData();button.setText(collapsed?item.icon():item.icon()+"   "+item.label());}for(Node node:sidebar.lookupAll(".nav-group-title,.sidebar-subtitle,.sidebar-user,.role-badge"))node.setVisible(!collapsed);}
    private void testDatabase(){Task<DatabaseConnection.ConnectionStatus> t=new Task<>(){protected DatabaseConnection.ConnectionStatus call(){return DatabaseConnection.test();}};t.setOnSucceeded(e->{var r=t.getValue();dbStatus.setText(r.connected()?"● Database connected":"● Database unavailable");dbStatus.getStyleClass().removeAll("connection-ok","connection-error");dbStatus.getStyleClass().add(r.connected()?"connection-ok":"connection-error");});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void loadNotificationCount(){if(!AppSession.isLoggedIn())return;int userId=AppSession.current().userId();Task<Object> task=new Task<>(){protected Object call()throws Exception{return new QueryDAO().scalar("SELECT COUNT(*) FROM notifications WHERE IsRead=0 AND (UserID IS NULL OR UserID=?)",java.util.List.of(userId));}};task.setOnSucceeded(e->{long value=task.getValue() instanceof Number n?n.longValue():0;notificationButton.setText(value>0?"Notifications ("+value+")":"Notifications");});Thread thread=new Thread(task,"notification-count");thread.setDaemon(true);thread.start();}
    private void startClock(){sessionTimeline=new Timeline(new KeyFrame(Duration.seconds(30),e->{lastRefresh.setText("Session active · "+LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));loadNotificationCount();}));sessionTimeline.setCycleCount(Timeline.INDEFINITE);sessionTimeline.play();}
}
