package com.lucerne.ui;

import com.lucerne.app.AppSession;
import com.lucerne.dao.ProductDAO;
import com.lucerne.dao.QueryDAO;
import com.lucerne.ui.components.LoadingPane;
import com.lucerne.ui.components.MetricCard;
import com.lucerne.util.AlertUtil;
import com.lucerne.util.ExportUtil;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.*;
import javafx.stage.FileChooser;

import java.io.File;
import java.math.BigDecimal;
import java.nio.file.Path;
import java.util.*;

public final class ProductsView extends StackPane {
    private final ProductDAO dao=new ProductDAO();private final TableView<Map<String,Object>> table=new TableView<>();
    private final TextField search=new TextField();private final ComboBox<QueryDAO.Option> category=new ComboBox<>();private final ComboBox<String> stock=new ComboBox<>();private final CheckBox inactive=new CheckBox("Include inactive");
    private final LoadingPane loading=new LoadingPane();private List<Map<String,Object>> rows=List.of();private List<String> columns=List.of();private int page=0,total=0;private final Label count=new Label();
    public ProductsView(){getChildren().addAll(build(),loading);loadCategories();load();}
    private VBox build(){VBox root=new VBox(18);root.setPadding(new Insets(24));root.getStyleClass().add("page-root");Label title=new Label("Products");title.getStyleClass().add("page-title");Label desc=new Label("One catalog for every category, variant, image, price, margin and stock location.");desc.getStyleClass().add("page-description");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);Button add=new Button("Add product");add.getStyleClass().add("primary-button");add.setOnAction(e->openForm(null));Button edit=new Button("Edit");edit.setOnAction(e->edit());Button active=new Button("Activate / deactivate");active.setOnAction(e->toggleActive());boolean manage=AppSession.hasPermission("MANAGE_PRODUCTS");add.setVisible(manage);add.setManaged(manage);edit.setVisible(manage);edit.setManaged(manage);active.setVisible(manage);active.setManaged(manage);Button export=new Button("Export filtered");export.setOnAction(e->export());Button refresh=new Button("Refresh");refresh.setOnAction(e->load());HBox head=new HBox(10,new VBox(4,title,desc),spacer,add,edit,active,export,refresh);head.setAlignment(Pos.CENTER_LEFT);
        FlowPane filters=new FlowPane(10,10);filters.getStyleClass().add("filter-panel");filters.setPadding(new Insets(14));search.setPromptText("Name, SKU or barcode");search.setPrefWidth(260);category.setPromptText("All categories");stock.getItems().addAll("All","In stock","Low stock","Out of stock");stock.setValue("All");Button apply=new Button("Apply filters");apply.getStyleClass().add("primary-button");apply.setOnAction(e->{page=0;load();});Button clear=new Button("Clear");clear.setOnAction(e->{search.clear();category.getSelectionModel().selectFirst();stock.setValue("All");inactive.setSelected(false);page=0;load();});filters.getChildren().addAll(search,category,stock,inactive,apply,clear);search.setOnAction(e->{page=0;load();});
        HBox cards=new HBox(14);for(String t:List.of("Filtered products","Visible stock","Visible retail value","Low / zero stock")){MetricCard c=new MetricCard(t);c.setValue("—");c.setPrefWidth(230);cards.getChildren().add(c);HBox.setHgrow(c,Priority.ALWAYS);}cards.setUserData(cards.getChildren());
        table.setPlaceholder(new Label("No products match these filters."));table.setColumnResizePolicy(TableView.UNCONSTRAINED_RESIZE_POLICY);table.setRowFactory(v->{TableRow<Map<String,Object>> r=new TableRow<>();r.setOnMouseClicked(e->{if(e.getClickCount()==2&&!r.isEmpty()){if(AppSession.hasPermission("MANAGE_PRODUCTS"))openForm(r.getItem());else showDetails(r.getItem());}});return r;});VBox card=new VBox(10,count,table);card.getStyleClass().add("content-card");card.setPadding(new Insets(14));VBox.setVgrow(table,Priority.ALWAYS);root.getChildren().addAll(head,cards,filters,card);VBox.setVgrow(card,Priority.ALWAYS);root.setUserData(cards);return root;}
    private void loadCategories(){Task<List<QueryDAO.Option>> t=new Task<>(){protected List<QueryDAO.Option> call()throws Exception{return dao.categories();}};t.setOnSucceeded(e->{category.getItems().setAll(new QueryDAO.Option(null,"All categories"));category.getItems().addAll(t.getValue());category.getSelectionModel().selectFirst();});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void load(){Integer cat=category.getValue()==null||category.getValue().id()==null?null:((Number)category.getValue().id()).intValue();loading.show("Loading product catalog…");Task<QueryDAO.QueryResult> t=new Task<>(){protected QueryDAO.QueryResult call()throws Exception{return dao.search(search.getText(),cat,stock.getValue(),inactive.isSelected(),AppSession.hasPermission("VIEW_PRODUCT_COST"),50,page*50);}};t.setOnSucceeded(e->{render(t.getValue());loading.hide();});t.setOnFailed(e->{loading.hide();AlertUtil.error("Products unavailable","The product catalog could not be loaded.");});Thread x=new Thread(t,"products-load");x.setDaemon(true);x.start();}
    private void render(QueryDAO.QueryResult result){rows=result.rows();columns=result.columns();total=result.total();table.getColumns().clear();for(String col:columns){TableColumn<Map<String,Object>,Object> c=new TableColumn<>(col);c.setCellValueFactory(v->new ReadOnlyObjectWrapper<>(v.getValue().get(col)));if(col.equals("Image")){c.setCellFactory(v->new TableCell<>(){private final ImageView image=new ImageView();{image.setFitWidth(52);image.setFitHeight(64);image.setPreserveRatio(true);}protected void updateItem(Object item,boolean empty){super.updateItem(item,empty);if(empty||item==null){setGraphic(null);return;}try{var stream=getClass().getResourceAsStream("/"+item);if(stream!=null){image.setImage(new Image(stream));setGraphic(image);}else setGraphic(null);}catch(Exception e){setGraphic(null);}}});c.setPrefWidth(80);}else{c.setCellFactory(v->new TableCell<>(){protected void updateItem(Object item,boolean empty){super.updateItem(item,empty);setText(empty||item==null?null:item instanceof BigDecimal b?String.format("%,.2f",b):String.valueOf(item));}});c.setPrefWidth(Math.max(100,Math.min(220,col.length()*12.0)));}table.getColumns().add(c);}table.getItems().setAll(rows);count.setText(total+" products match the current filters");updateCards();}
    @SuppressWarnings("unchecked") private void updateCards(){VBox root=(VBox)getChildren().getFirst();HBox cards=(HBox)root.getUserData();List<javafx.scene.Node> nodes=cards.getChildren();int stockSum=0,low=0;BigDecimal value=BigDecimal.ZERO;for(Map<String,Object> r:rows){int q=((Number)r.getOrDefault("Stock",0)).intValue();stockSum+=q;if(q<=((Number)r.getOrDefault("Reorder Level",0)).intValue())low++;Object p=r.get("Price");if(p instanceof BigDecimal b)value=value.add(b.multiply(BigDecimal.valueOf(q)));}((MetricCard)nodes.get(0)).setValue(String.valueOf(total));((MetricCard)nodes.get(1)).setValue(String.valueOf(stockSum));((MetricCard)nodes.get(2)).setValue(String.format("%,.2f",value));((MetricCard)nodes.get(3)).setValue(String.valueOf(low));}

    private void showDetails(Map<String,Object> row){
        Dialog<Void> dialog=new Dialog<>();dialog.setTitle("Product details");dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);
        GridPane grid=new GridPane();grid.setHgap(14);grid.setVgap(10);grid.setPadding(new Insets(18));int index=0;
        for(var entry:row.entrySet()){if(Set.of("Cost","Margin","Margin %").contains(entry.getKey())&&!AppSession.hasPermission("VIEW_PRODUCT_COST"))continue;Label key=new Label(entry.getKey());key.getStyleClass().add("detail-label");Label value=new Label(entry.getValue()==null?"—":String.valueOf(entry.getValue()));value.setWrapText(true);grid.addRow(index++,key,value);}
        ScrollPane scroll=new ScrollPane(grid);scroll.setFitToWidth(true);scroll.setPrefViewportWidth(620);scroll.setPrefViewportHeight(480);dialog.getDialogPane().setContent(scroll);dialog.showAndWait();
    }
    private Map<String,Object> selected(){Map<String,Object> r=table.getSelectionModel().getSelectedItem();if(r==null)AlertUtil.warning("Select a product","Choose a product row first.");return r;}
    private void edit(){Map<String,Object> r=selected();if(r!=null)openForm(r);}
    private void toggleActive(){Map<String,Object> r=selected();if(r==null)return;boolean active=asBoolean(r.get("Active"));if(!AlertUtil.confirm(active?"Deactivate product":"Reactivate product","Historical sales will remain unchanged. Continue?"))return;Task<Void> t=new Task<>(){protected Void call()throws Exception{dao.setActive(((Number)r.get("Product ID")).intValue(),!active,AppSession.current().userId());return null;}};t.setOnSucceeded(e->load());t.setOnFailed(e->AlertUtil.error("Update failed","Product status could not be changed."));Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private boolean asBoolean(Object v){return v instanceof Boolean b?b:v instanceof Number n&&n.intValue()!=0;}
    private void openForm(Map<String,Object> row){Dialog<ProductDAO.ProductForm> d=new Dialog<>();d.setTitle(row==null?"Add product":"Edit product");d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);GridPane g=new GridPane();g.setHgap(12);g.setVgap(10);g.setPadding(new Insets(18));TextField sku=f(row,"SKU"),barcode=f(row,"Barcode"),name=f(row,"Product"),price=f(row,"Price"),cost=f(row,"Cost"),reorder=f(row,"Reorder Level"),description=f(row,"Description"),material=f(row,"Material"),care=f(row,"Care Instructions"),image=f(row,"Image");ComboBox<QueryDAO.Option> cat=new ComboBox<>();cat.getItems().addAll(category.getItems().stream().filter(o->o.id()!=null).toList());if(row!=null)cat.getItems().stream().filter(o->o.label().equals(String.valueOf(row.get("Category")))).findFirst().ifPresent(cat::setValue);ComboBox<QueryDAO.Option> sub=new ComboBox<>();cat.setOnAction(e->loadSubcategories(cat,sub));if(cat.getValue()!=null)loadSubcategories(cat,sub);Button choose=new Button("Choose local image");choose.setOnAction(e->{FileChooser fc=new FileChooser();fc.getExtensionFilters().add(new FileChooser.ExtensionFilter("Images","*.png","*.jpg","*.jpeg"));File file=fc.showOpenDialog(getScene().getWindow());if(file!=null)image.setText(file.toURI().toString());});int i=0;g.addRow(i++,new Label("SKU*"),sku);g.addRow(i++,new Label("Barcode"),barcode);g.addRow(i++,new Label("Name*"),name);g.addRow(i++,new Label("Category*"),cat);g.addRow(i++,new Label("Subcategory"),sub);g.addRow(i++,new Label("Selling price*"),price);g.addRow(i++,new Label("Cost price*"),cost);g.addRow(i++,new Label("Reorder level*"),reorder);g.addRow(i++,new Label("Description"),description);g.addRow(i++,new Label("Material"),material);g.addRow(i++,new Label("Care"),care);g.addRow(i++,new Label("Image path"),new HBox(8,image,choose));ScrollPane sc=new ScrollPane(g);sc.setFitToWidth(true);sc.setPrefViewportHeight(560);d.getDialogPane().setContent(sc);d.setResultConverter(b->{if(b!=ButtonType.OK)return null;try{if(name.getText().isBlank()||sku.getText().isBlank()||cat.getValue()==null)throw new IllegalArgumentException();BigDecimal p=new BigDecimal(price.getText()),c=new BigDecimal(cost.getText());if(p.signum()<0||c.signum()<0)throw new IllegalArgumentException();return new ProductDAO.ProductForm(sku.getText().trim(),barcode.getText().trim(),name.getText().trim(),((Number)cat.getValue().id()).intValue(),sub.getValue()==null?null:((Number)sub.getValue().id()).intValue(),p,c,description.getText().trim(),material.getText().trim(),care.getText().trim(),image.getText().trim(),Integer.parseInt(reorder.getText()));}catch(Exception e){AlertUtil.warning("Invalid product","Complete required fields and use valid non-negative prices and stock level.");return null;}});Optional<ProductDAO.ProductForm> result=d.showAndWait();result.ifPresent(form->save(row,form));}
    private TextField f(Map<String,Object> row,String key){TextField t=new TextField(row==null?"":String.valueOf(row.getOrDefault(key,"")));return t;}
    private void loadSubcategories(ComboBox<QueryDAO.Option> cat,ComboBox<QueryDAO.Option> sub){if(cat.getValue()==null)return;Task<List<QueryDAO.Option>> t=new Task<>(){protected List<QueryDAO.Option> call()throws Exception{return dao.subcategories(((Number)cat.getValue().id()).intValue());}};t.setOnSucceeded(e->sub.getItems().setAll(t.getValue()));Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void save(Map<String,Object> row,ProductDAO.ProductForm form){loading.show("Saving product…");Task<Void> t=new Task<>(){protected Void call()throws Exception{if(row==null)dao.create(form,AppSession.current().userId());else dao.update(((Number)row.get("Product ID")).intValue(),form,AppSession.current().userId());return null;}};t.setOnSucceeded(e->{loading.hide();AlertUtil.info("Saved","Product saved successfully.");load();});t.setOnFailed(e->{loading.hide();AlertUtil.error("Save failed","Check duplicate SKU/barcode and database constraints.");});Thread x=new Thread(t);x.setDaemon(true);x.start();}
    private void export(){if(rows.isEmpty()){AlertUtil.warning("Nothing to export","No products are currently visible.");return;}Path p=ExportUtil.chooseCsv(getScene().getWindow(),"products-filtered.csv");if(p==null)return;try{ExportUtil.writeCsv(p,columns,rows);AlertUtil.info("Export complete",p.toString());}catch(Exception e){AlertUtil.error("Export failed","Could not create CSV file.");}}
}
