-- Lucerne Boutique Professional Database
-- MySQL 8.0+
-- Fresh development/demo installation. Import into a test database first.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
DROP DATABASE IF EXISTS lucerne_demo;
CREATE DATABASE lucerne_demo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lucerne_demo;

CREATE TABLE roles (
 RoleID INT AUTO_INCREMENT PRIMARY KEY, RoleName VARCHAR(30) NOT NULL UNIQUE, Description VARCHAR(255), IsSystemRole BOOLEAN NOT NULL DEFAULT TRUE, CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE permissions (
 PermissionID INT AUTO_INCREMENT PRIMARY KEY, PermissionCode VARCHAR(80) NOT NULL UNIQUE, Description VARCHAR(255)
) ENGINE=InnoDB;
CREATE TABLE role_permissions (RoleID INT NOT NULL,PermissionID INT NOT NULL,PRIMARY KEY(RoleID,PermissionID),FOREIGN KEY(RoleID) REFERENCES roles(RoleID),FOREIGN KEY(PermissionID) REFERENCES permissions(PermissionID)) ENGINE=InnoDB;
CREATE TABLE branches (BranchID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(100) NOT NULL UNIQUE,Location VARCHAR(255),Phone VARCHAR(30),IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE warehouses (WarehouseID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(100) NOT NULL UNIQUE,Location VARCHAR(255),Phone VARCHAR(30),IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users (
 UserID INT AUTO_INCREMENT PRIMARY KEY,FullName VARCHAR(120) NOT NULL,Username VARCHAR(60) NOT NULL UNIQUE,PasswordHash VARCHAR(100),LegacyPassword VARCHAR(255),RoleID INT NOT NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,PasswordChangeRequired BOOLEAN NOT NULL DEFAULT FALSE,FailedLoginCount INT NOT NULL DEFAULT 0,LockedUntil DATETIME NULL,AccountExpiresAt DATETIME NULL,LastLoginAt DATETIME NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CreatedBy INT NULL,UpdatedBy INT NULL,FOREIGN KEY(RoleID) REFERENCES roles(RoleID),FOREIGN KEY(CreatedBy) REFERENCES users(UserID) ON DELETE SET NULL,FOREIGN KEY(UpdatedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_users_role_active(RoleID,IsActive),INDEX idx_users_last_login(LastLoginAt)
) ENGINE=InnoDB;
CREATE TABLE user_permissions (UserID INT NOT NULL,PermissionID INT NOT NULL,IsGranted BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(UserID,PermissionID),FOREIGN KEY(UserID) REFERENCES users(UserID),FOREIGN KEY(PermissionID) REFERENCES permissions(PermissionID)) ENGINE=InnoDB;
CREATE TABLE employees (
 EmployeeID INT AUTO_INCREMENT PRIMARY KEY,UserID INT NULL UNIQUE,FullName VARCHAR(120) NOT NULL,Phone VARCHAR(30),Email VARCHAR(120),JobTitle VARCHAR(100) NOT NULL,BranchID INT NULL,WarehouseID INT NULL,Salary DECIMAL(12,2) NOT NULL DEFAULT 0,HireDate DATE NOT NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(UserID) REFERENCES users(UserID) ON DELETE SET NULL,FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(WarehouseID) REFERENCES warehouses(WarehouseID),CHECK(Salary>=0),INDEX idx_employee_branch(BranchID,IsActive),INDEX idx_employee_warehouse(WarehouseID,IsActive)
) ENGINE=InnoDB;
CREATE TABLE customers (
 CustomerID INT AUTO_INCREMENT PRIMARY KEY,UserID INT NULL UNIQUE,FullName VARCHAR(120) NOT NULL,Phone VARCHAR(30) NOT NULL,Email VARCHAR(120),RegisteredAt DATE NOT NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,VIPStatus VARCHAR(20) NOT NULL DEFAULT 'REGULAR',CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(UserID) REFERENCES users(UserID) ON DELETE SET NULL,UNIQUE KEY uq_customer_phone(Phone),INDEX idx_customer_name(FullName),INDEX idx_customer_registered(RegisteredAt)
) ENGINE=InnoDB;
CREATE TABLE categories (CategoryID INT AUTO_INCREMENT PRIMARY KEY,CategoryName VARCHAR(80) NOT NULL UNIQUE,Description VARCHAR(255),IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE subcategories (SubcategoryID INT AUTO_INCREMENT PRIMARY KEY,CategoryID INT NOT NULL,SubcategoryName VARCHAR(80) NOT NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(CategoryID) REFERENCES categories(CategoryID),UNIQUE KEY uq_subcategory(CategoryID,SubcategoryName)) ENGINE=InnoDB;
CREATE TABLE sizes (SizeID INT AUTO_INCREMENT PRIMARY KEY,SizeValue VARCHAR(20) NOT NULL UNIQUE,SortOrder INT NOT NULL DEFAULT 0,IsActive BOOLEAN NOT NULL DEFAULT TRUE) ENGINE=InnoDB;
CREATE TABLE colors (ColorID INT AUTO_INCREMENT PRIMARY KEY,ColorName VARCHAR(40) NOT NULL UNIQUE,HexCode VARCHAR(7),IsActive BOOLEAN NOT NULL DEFAULT TRUE) ENGINE=InnoDB;
CREATE TABLE products (
 ProductID INT AUTO_INCREMENT PRIMARY KEY,SKU VARCHAR(40) NOT NULL UNIQUE,Barcode VARCHAR(60) NULL UNIQUE,Name VARCHAR(140) NOT NULL,CategoryID INT NOT NULL,SubcategoryID INT NULL,SellingPrice DECIMAL(12,2) NOT NULL,CostPrice DECIMAL(12,2) NOT NULL,Description TEXT,Material VARCHAR(120),CareInstructions VARCHAR(255),ImagePath VARCHAR(255),ReorderLevel INT NOT NULL DEFAULT 5,IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedBy INT NULL,UpdatedBy INT NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(CategoryID) REFERENCES categories(CategoryID),FOREIGN KEY(SubcategoryID) REFERENCES subcategories(SubcategoryID),FOREIGN KEY(CreatedBy) REFERENCES users(UserID) ON DELETE SET NULL,FOREIGN KEY(UpdatedBy) REFERENCES users(UserID) ON DELETE SET NULL,CHECK(SellingPrice>=0),CHECK(CostPrice>=0),CHECK(ReorderLevel>=0),INDEX idx_products_category_active(CategoryID,IsActive),INDEX idx_products_name(Name)
) ENGINE=InnoDB;
CREATE TABLE product_variants (VariantID INT AUTO_INCREMENT PRIMARY KEY,ProductID INT NOT NULL,SizeID INT NOT NULL,ColorID INT NOT NULL,VariantSKU VARCHAR(60) UNIQUE,VariantBarcode VARCHAR(60) UNIQUE,IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(ProductID) REFERENCES products(ProductID),FOREIGN KEY(SizeID) REFERENCES sizes(SizeID),FOREIGN KEY(ColorID) REFERENCES colors(ColorID),UNIQUE KEY uq_variant(ProductID,SizeID,ColorID),INDEX idx_variant_product(ProductID,IsActive)) ENGINE=InnoDB;
CREATE TABLE branch_inventory (BranchInventoryID BIGINT AUTO_INCREMENT PRIMARY KEY,BranchID INT NOT NULL,VariantID INT NOT NULL,Quantity INT NOT NULL DEFAULT 0,ReorderLevel INT NOT NULL DEFAULT 5,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),UNIQUE KEY uq_branch_variant(BranchID,VariantID),CHECK(Quantity>=0),INDEX idx_branch_stock(BranchID,Quantity,ReorderLevel)) ENGINE=InnoDB;
CREATE TABLE warehouse_inventory (WarehouseInventoryID BIGINT AUTO_INCREMENT PRIMARY KEY,WarehouseID INT NOT NULL,VariantID INT NOT NULL,Quantity INT NOT NULL DEFAULT 0,ReorderLevel INT NOT NULL DEFAULT 10,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(WarehouseID) REFERENCES warehouses(WarehouseID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),UNIQUE KEY uq_warehouse_variant(WarehouseID,VariantID),CHECK(Quantity>=0),INDEX idx_warehouse_stock(WarehouseID,Quantity,ReorderLevel)) ENGINE=InnoDB;
CREATE TABLE price_history (PriceHistoryID BIGINT AUTO_INCREMENT PRIMARY KEY,ProductID INT NOT NULL,OldPrice DECIMAL(12,2),NewPrice DECIMAL(12,2),ChangedBy INT NULL,ChangedAt DATETIME NOT NULL,FOREIGN KEY(ProductID) REFERENCES products(ProductID),FOREIGN KEY(ChangedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_price_product_date(ProductID,ChangedAt)) ENGINE=InnoDB;
CREATE TABLE discounts (DiscountID INT AUTO_INCREMENT PRIMARY KEY,Code VARCHAR(40) NOT NULL UNIQUE,Description VARCHAR(255),Percentage DECIMAL(5,2) DEFAULT 0,FixedAmount DECIMAL(12,2) DEFAULT 0,MinimumPurchase DECIMAL(12,2) DEFAULT 0,MaximumDiscount DECIMAL(12,2) NULL,StartDate DATE NOT NULL,EndDate DATE NOT NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedBy INT NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(CreatedBy) REFERENCES users(UserID) ON DELETE SET NULL,CHECK(Percentage BETWEEN 0 AND 100),CHECK(EndDate>=StartDate)) ENGINE=InnoDB;
CREATE TABLE sales (
 SaleID BIGINT AUTO_INCREMENT PRIMARY KEY,ReceiptNumber VARCHAR(50) NOT NULL UNIQUE,BranchID INT NOT NULL,CustomerID INT NULL,CashierUserID INT NOT NULL,SaleDate DATETIME NOT NULL,GrossAmount DECIMAL(14,2) NOT NULL DEFAULT 0,DiscountID INT NULL,DiscountAmount DECIMAL(14,2) NOT NULL DEFAULT 0,NetAmount DECIMAL(14,2) NOT NULL DEFAULT 0,CostAmount DECIMAL(14,2) NOT NULL DEFAULT 0,GrossProfit DECIMAL(14,2) NOT NULL DEFAULT 0,PaymentMethod VARCHAR(30) NOT NULL,Status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(CustomerID) REFERENCES customers(CustomerID),FOREIGN KEY(CashierUserID) REFERENCES users(UserID),FOREIGN KEY(DiscountID) REFERENCES discounts(DiscountID),CHECK(GrossAmount>=0),CHECK(DiscountAmount>=0),CHECK(NetAmount>=0),INDEX idx_sales_date_branch(SaleDate,BranchID),INDEX idx_sales_cashier_date(CashierUserID,SaleDate),INDEX idx_sales_customer(CustomerID,SaleDate),INDEX idx_sales_status(Status)
) ENGINE=InnoDB;
CREATE TABLE sale_items (SaleItemID BIGINT AUTO_INCREMENT PRIMARY KEY,SaleID BIGINT NOT NULL,VariantID INT NOT NULL,Quantity INT NOT NULL,UnitPrice DECIMAL(12,2) NOT NULL,DiscountAmount DECIMAL(12,2) NOT NULL DEFAULT 0,LineTotal DECIMAL(14,2) NOT NULL,CostAtSale DECIMAL(12,2) NOT NULL,ReturnedQuantity INT NOT NULL DEFAULT 0,FOREIGN KEY(SaleID) REFERENCES sales(SaleID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(Quantity>0),CHECK(ReturnedQuantity BETWEEN 0 AND Quantity),INDEX idx_sale_items_sale(SaleID),INDEX idx_sale_items_variant(VariantID)) ENGINE=InnoDB;
CREATE TABLE payments (PaymentID BIGINT AUTO_INCREMENT PRIMARY KEY,SaleID BIGINT NOT NULL,PaymentMethod VARCHAR(30) NOT NULL,Amount DECIMAL(14,2) NOT NULL,PaidAmount DECIMAL(14,2) NOT NULL,ChangeAmount DECIMAL(14,2) NOT NULL DEFAULT 0,PaymentDate DATETIME NOT NULL,Status VARCHAR(20) NOT NULL,ReferenceNumber VARCHAR(80),FOREIGN KEY(SaleID) REFERENCES sales(SaleID),INDEX idx_payment_sale(SaleID),INDEX idx_payment_date(PaymentDate)) ENGINE=InnoDB;
CREATE TABLE cash_drawer_movements (MovementID BIGINT AUTO_INCREMENT PRIMARY KEY,CashierUserID INT NOT NULL,BranchID INT NOT NULL,MovementType VARCHAR(30) NOT NULL,Amount DECIMAL(14,2) NOT NULL,MovementDate DATETIME NOT NULL,ReferenceNumber VARCHAR(80),Notes VARCHAR(255),FOREIGN KEY(CashierUserID) REFERENCES users(UserID),FOREIGN KEY(BranchID) REFERENCES branches(BranchID),INDEX idx_cashier_movement(CashierUserID,MovementDate)) ENGINE=InnoDB;
CREATE TABLE online_orders (OrderID BIGINT AUTO_INCREMENT PRIMARY KEY,OrderNumber VARCHAR(50) NOT NULL UNIQUE,CustomerID INT NOT NULL,BranchID INT NULL,OrderDate DATETIME NOT NULL,OrderType VARCHAR(20) NOT NULL DEFAULT 'ONLINE',DeliveryType VARCHAR(20) NOT NULL,DeliveryAddress VARCHAR(255),PaymentStatus VARCHAR(25) NOT NULL DEFAULT 'PENDING',Status VARCHAR(30) NOT NULL DEFAULT 'PENDING',Subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,DiscountAmount DECIMAL(14,2) NOT NULL DEFAULT 0,DeliveryFee DECIMAL(12,2) NOT NULL DEFAULT 0,TotalAmount DECIMAL(14,2) NOT NULL DEFAULT 0,AssignedEmployeeID INT NULL,Notes VARCHAR(255),CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(CustomerID) REFERENCES customers(CustomerID),FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(AssignedEmployeeID) REFERENCES employees(EmployeeID),INDEX idx_orders_date_status(OrderDate,Status),INDEX idx_orders_branch(BranchID,Status),INDEX idx_orders_customer(CustomerID,OrderDate)) ENGINE=InnoDB;
CREATE TABLE order_items (OrderItemID BIGINT AUTO_INCREMENT PRIMARY KEY,OrderID BIGINT NOT NULL,VariantID INT NOT NULL,Quantity INT NOT NULL,UnitPrice DECIMAL(12,2) NOT NULL,LineTotal DECIMAL(14,2) NOT NULL,FOREIGN KEY(OrderID) REFERENCES online_orders(OrderID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(Quantity>0),INDEX idx_order_items_order(OrderID)) ENGINE=InnoDB;
CREATE TABLE order_status_history (HistoryID BIGINT AUTO_INCREMENT PRIMARY KEY,OrderID BIGINT NOT NULL,Status VARCHAR(30) NOT NULL,Notes VARCHAR(255),ChangedBy INT NULL,ChangedAt DATETIME NOT NULL,FOREIGN KEY(OrderID) REFERENCES online_orders(OrderID),FOREIGN KEY(ChangedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_order_history(OrderID,ChangedAt)) ENGINE=InnoDB;
CREATE TABLE return_requests (ReturnID BIGINT AUTO_INCREMENT PRIMARY KEY,RequestNumber VARCHAR(50) NOT NULL UNIQUE,SaleID BIGINT NOT NULL,CustomerID INT NULL,BranchID INT NOT NULL,RequestType VARCHAR(20) NOT NULL,RequestDate DATETIME NOT NULL,Reason VARCHAR(255) NOT NULL,ItemCondition VARCHAR(80),RefundMethod VARCHAR(30),RefundAmount DECIMAL(14,2) NOT NULL DEFAULT 0,Status VARCHAR(30) NOT NULL DEFAULT 'PENDING',RequestedBy INT NULL,ApprovedBy INT NULL,ProcessedAt DATETIME NULL,FOREIGN KEY(SaleID) REFERENCES sales(SaleID),FOREIGN KEY(CustomerID) REFERENCES customers(CustomerID),FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(RequestedBy) REFERENCES users(UserID) ON DELETE SET NULL,FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_returns_date_status(RequestDate,Status),INDEX idx_returns_branch(BranchID,Status)) ENGINE=InnoDB;
CREATE TABLE return_items (ReturnItemID BIGINT AUTO_INCREMENT PRIMARY KEY,ReturnID BIGINT NOT NULL,SaleItemID BIGINT NOT NULL,Quantity INT NOT NULL,RefundAmount DECIMAL(14,2) NOT NULL,RestoreInventory BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(ReturnID) REFERENCES return_requests(ReturnID),FOREIGN KEY(SaleItemID) REFERENCES sale_items(SaleItemID),CHECK(Quantity>0)) ENGINE=InnoDB;
CREATE TABLE expenses (ExpenseID BIGINT AUTO_INCREMENT PRIMARY KEY,ExpenseDate DATE NOT NULL,Category VARCHAR(80) NOT NULL,Description VARCHAR(255) NOT NULL,BranchID INT NULL,Amount DECIMAL(14,2) NOT NULL,PaymentMethod VARCHAR(30),IsRecurring BOOLEAN NOT NULL DEFAULT FALSE,Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',ReceiptPath VARCHAR(255),RecordedBy INT NOT NULL,ApprovedBy INT NULL,ApprovedAt DATETIME NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(RecordedBy) REFERENCES users(UserID),FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,CHECK(Amount>=0),INDEX idx_expense_date_branch(ExpenseDate,BranchID),INDEX idx_expense_status(Status)) ENGINE=InnoDB;
CREATE TABLE suppliers (SupplierID INT AUTO_INCREMENT PRIMARY KEY,SupplierCode VARCHAR(30) NOT NULL UNIQUE,SupplierName VARCHAR(120) NOT NULL,ContactPerson VARCHAR(120),Phone VARCHAR(30),Email VARCHAR(120),Address VARCHAR(255),Notes VARCHAR(255),IsActive BOOLEAN NOT NULL DEFAULT TRUE,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_supplier_name(SupplierName)) ENGINE=InnoDB;
CREATE TABLE supplier_products (SupplierID INT NOT NULL,ProductID INT NOT NULL,SupplierSKU VARCHAR(60),LastCost DECIMAL(12,2),LeadTimeDays INT,PRIMARY KEY(SupplierID,ProductID),FOREIGN KEY(SupplierID) REFERENCES suppliers(SupplierID),FOREIGN KEY(ProductID) REFERENCES products(ProductID)) ENGINE=InnoDB;
CREATE TABLE purchase_orders (PurchaseOrderID BIGINT AUTO_INCREMENT PRIMARY KEY,PONumber VARCHAR(50) NOT NULL UNIQUE,SupplierID INT NOT NULL,WarehouseID INT NOT NULL,OrderDate DATE NOT NULL,ExpectedDate DATE NULL,TotalCost DECIMAL(14,2) NOT NULL DEFAULT 0,Status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',Notes VARCHAR(255),CreatedBy INT NOT NULL,ApprovedBy INT NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(SupplierID) REFERENCES suppliers(SupplierID),FOREIGN KEY(WarehouseID) REFERENCES warehouses(WarehouseID),FOREIGN KEY(CreatedBy) REFERENCES users(UserID),FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_po_date_status(OrderDate,Status)) ENGINE=InnoDB;
CREATE TABLE purchase_order_items (PurchaseOrderItemID BIGINT AUTO_INCREMENT PRIMARY KEY,PurchaseOrderID BIGINT NOT NULL,VariantID INT NOT NULL,OrderedQuantity INT NOT NULL,ReceivedQuantity INT NOT NULL DEFAULT 0,UnitCost DECIMAL(12,2) NOT NULL,LineTotal DECIMAL(14,2) NOT NULL,FOREIGN KEY(PurchaseOrderID) REFERENCES purchase_orders(PurchaseOrderID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(OrderedQuantity>0),CHECK(ReceivedQuantity>=0)) ENGINE=InnoDB;
CREATE TABLE goods_receipts (ReceiptID BIGINT AUTO_INCREMENT PRIMARY KEY,ReceiptNumber VARCHAR(50) NOT NULL UNIQUE,PurchaseOrderID BIGINT NOT NULL,WarehouseID INT NOT NULL,ReceivedDate DATETIME NOT NULL,ReceivedBy INT NOT NULL,Notes VARCHAR(255),FOREIGN KEY(PurchaseOrderID) REFERENCES purchase_orders(PurchaseOrderID),FOREIGN KEY(WarehouseID) REFERENCES warehouses(WarehouseID),FOREIGN KEY(ReceivedBy) REFERENCES users(UserID)) ENGINE=InnoDB;
CREATE TABLE goods_receipt_items (ReceiptItemID BIGINT AUTO_INCREMENT PRIMARY KEY,ReceiptID BIGINT NOT NULL,VariantID INT NOT NULL,ReceivedQuantity INT NOT NULL,DamagedQuantity INT NOT NULL DEFAULT 0,UnitCost DECIMAL(12,2) NOT NULL,FOREIGN KEY(ReceiptID) REFERENCES goods_receipts(ReceiptID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(ReceivedQuantity>=0),CHECK(DamagedQuantity>=0)) ENGINE=InnoDB;
CREATE TABLE stock_requests (RequestID BIGINT AUTO_INCREMENT PRIMARY KEY,RequestNumber VARCHAR(50) NOT NULL UNIQUE,BranchID INT NOT NULL,WarehouseID INT NOT NULL,RequestedBy INT NOT NULL,RequestDate DATETIME NOT NULL,Priority VARCHAR(15) NOT NULL DEFAULT 'NORMAL',Status VARCHAR(30) NOT NULL DEFAULT 'PENDING',ApprovedBy INT NULL,ApprovedAt DATETIME NULL,Notes VARCHAR(255),FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(WarehouseID) REFERENCES warehouses(WarehouseID),FOREIGN KEY(RequestedBy) REFERENCES users(UserID),FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_request_date_status(RequestDate,Status),INDEX idx_request_branch(BranchID,Status)) ENGINE=InnoDB;
CREATE TABLE stock_request_items (RequestItemID BIGINT AUTO_INCREMENT PRIMARY KEY,RequestID BIGINT NOT NULL,VariantID INT NOT NULL,RequestedQuantity INT NOT NULL,ApprovedQuantity INT NOT NULL DEFAULT 0,FulfilledQuantity INT NOT NULL DEFAULT 0,FOREIGN KEY(RequestID) REFERENCES stock_requests(RequestID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(RequestedQuantity>0),CHECK(ApprovedQuantity>=0),CHECK(FulfilledQuantity>=0)) ENGINE=InnoDB;
CREATE TABLE stock_transfers (TransferID BIGINT AUTO_INCREMENT PRIMARY KEY,TransferNumber VARCHAR(50) NOT NULL UNIQUE,FromLocationType VARCHAR(20) NOT NULL,FromLocationID INT NOT NULL,ToLocationType VARCHAR(20) NOT NULL,ToLocationID INT NOT NULL,TransferDate DATETIME NOT NULL,Status VARCHAR(30) NOT NULL,CreatedBy INT NOT NULL,ApprovedBy INT NULL,Notes VARCHAR(255),FOREIGN KEY(CreatedBy) REFERENCES users(UserID),FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_transfer_date(TransferDate,Status)) ENGINE=InnoDB;
CREATE TABLE stock_transfer_items (TransferItemID BIGINT AUTO_INCREMENT PRIMARY KEY,TransferID BIGINT NOT NULL,VariantID INT NOT NULL,Quantity INT NOT NULL,FOREIGN KEY(TransferID) REFERENCES stock_transfers(TransferID),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),CHECK(Quantity>0)) ENGINE=InnoDB;
CREATE TABLE stock_movements (StockMovementID BIGINT AUTO_INCREMENT PRIMARY KEY,LocationType VARCHAR(20) NOT NULL,LocationID INT NOT NULL,VariantID INT NOT NULL,MovementType VARCHAR(30) NOT NULL,Direction VARCHAR(5) NOT NULL,Quantity INT NOT NULL,ReferenceType VARCHAR(30),ReferenceID BIGINT,ReferenceNumber VARCHAR(80),MovementDate DATETIME NOT NULL,PerformedBy INT NULL,Notes VARCHAR(255),FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),FOREIGN KEY(PerformedBy) REFERENCES users(UserID) ON DELETE SET NULL,CHECK(Quantity>0),INDEX idx_stock_movement_date(MovementDate),INDEX idx_stock_movement_location(LocationType,LocationID,MovementDate),INDEX idx_stock_movement_variant(VariantID,MovementDate)) ENGINE=InnoDB;
CREATE TABLE daily_closings (ClosingID BIGINT AUTO_INCREMENT PRIMARY KEY,ClosingDate DATE NOT NULL,BranchID INT NOT NULL,CashierUserID INT NOT NULL,ShiftStart DATETIME NOT NULL,ShiftEnd DATETIME NOT NULL,OpeningCash DECIMAL(14,2) NOT NULL,ExpectedCash DECIMAL(14,2) NOT NULL,ActualCash DECIMAL(14,2) NOT NULL,DifferenceAmount DECIMAL(14,2) NOT NULL,CashSales DECIMAL(14,2) NOT NULL DEFAULT 0,CardSales DECIMAL(14,2) NOT NULL DEFAULT 0,Refunds DECIMAL(14,2) NOT NULL DEFAULT 0,Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',Notes VARCHAR(255),ApprovedBy INT NULL,ApprovedAt DATETIME NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(BranchID) REFERENCES branches(BranchID),FOREIGN KEY(CashierUserID) REFERENCES users(UserID),FOREIGN KEY(ApprovedBy) REFERENCES users(UserID) ON DELETE SET NULL,UNIQUE KEY uq_closing_shift(CashierUserID,ClosingDate,ShiftStart),INDEX idx_closing_date_branch(ClosingDate,BranchID)) ENGINE=InnoDB;
CREATE TABLE damaged_stock (DamagedID BIGINT AUTO_INCREMENT PRIMARY KEY,LocationType VARCHAR(20),LocationID INT,VariantID INT NOT NULL,Quantity INT NOT NULL,Reason VARCHAR(255),RecordedBy INT NOT NULL,RecordedAt DATETIME NOT NULL,FOREIGN KEY(VariantID) REFERENCES product_variants(VariantID),FOREIGN KEY(RecordedBy) REFERENCES users(UserID)) ENGINE=InnoDB;
CREATE TABLE favorites (FavoriteID BIGINT AUTO_INCREMENT PRIMARY KEY,CustomerID INT NOT NULL,ProductID INT NOT NULL,CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(CustomerID) REFERENCES customers(CustomerID),FOREIGN KEY(ProductID) REFERENCES products(ProductID),UNIQUE KEY uq_favorite(CustomerID,ProductID)) ENGINE=InnoDB;
CREATE TABLE notifications (NotificationID BIGINT AUTO_INCREMENT PRIMARY KEY,UserID INT NULL,Title VARCHAR(140) NOT NULL,Message VARCHAR(500) NOT NULL,NotificationType VARCHAR(50) NOT NULL,Priority VARCHAR(15) NOT NULL DEFAULT 'NORMAL',RelatedEntityType VARCHAR(50),RelatedEntityID BIGINT,IsRead BOOLEAN NOT NULL DEFAULT FALSE,CreatedAt DATETIME NOT NULL,ReadAt DATETIME NULL,FOREIGN KEY(UserID) REFERENCES users(UserID) ON DELETE CASCADE,INDEX idx_notification_user_read(UserID,IsRead,CreatedAt)) ENGINE=InnoDB;
CREATE TABLE system_settings (SettingKey VARCHAR(80) PRIMARY KEY,SettingValue TEXT NOT NULL,Description VARCHAR(255),UpdatedBy INT NULL,UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(UpdatedBy) REFERENCES users(UserID) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE user_sessions (SessionID BIGINT AUTO_INCREMENT PRIMARY KEY,SessionIdentifier VARCHAR(80) NOT NULL UNIQUE,UserID INT NOT NULL,LoginAt DATETIME NOT NULL,LogoutAt DATETIME NULL,IsActive BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(UserID) REFERENCES users(UserID),INDEX idx_session_user_active(UserID,IsActive)) ENGINE=InnoDB;
CREATE TABLE login_attempts (AttemptID BIGINT AUTO_INCREMENT PRIMARY KEY,UserID INT NULL,UsernameAttempted VARCHAR(60),Success BOOLEAN NOT NULL,FailureReason VARCHAR(120),AttemptedAt DATETIME NOT NULL,FOREIGN KEY(UserID) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_login_attempt_date(AttemptedAt),INDEX idx_login_attempt_user(UserID,AttemptedAt)) ENGINE=InnoDB;
CREATE TABLE audit_logs (AuditID BIGINT AUTO_INCREMENT PRIMARY KEY,UserID INT NULL,Username VARCHAR(60),ActionCode VARCHAR(80) NOT NULL,EntityType VARCHAR(50),EntityID BIGINT,OldValue JSON NULL,NewValue JSON NULL,Description VARCHAR(500),ActionAt DATETIME NOT NULL,BranchID INT NULL,SessionIdentifier VARCHAR(80),Success BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(UserID) REFERENCES users(UserID) ON DELETE SET NULL,FOREIGN KEY(BranchID) REFERENCES branches(BranchID) ON DELETE SET NULL,INDEX idx_audit_date(ActionAt),INDEX idx_audit_user(UserID,ActionAt),INDEX idx_audit_entity(EntityType,EntityID)) ENGINE=InnoDB;
CREATE TABLE backup_history (BackupID BIGINT AUTO_INCREMENT PRIMARY KEY,BackupPath VARCHAR(500) NOT NULL,BackupType VARCHAR(20) NOT NULL,Status VARCHAR(20) NOT NULL,ErrorMessage VARCHAR(500),CreatedBy INT NULL,StartedAt DATETIME NOT NULL,CompletedAt DATETIME NULL,FOREIGN KEY(CreatedBy) REFERENCES users(UserID) ON DELETE SET NULL,INDEX idx_backup_status_date(Status,CompletedAt)) ENGINE=InnoDB;

-- Safe views
CREATE VIEW v_current_inventory AS
SELECT 'BRANCH' LocationType,b.Name LocationName,p.ProductID,pv.VariantID,p.SKU,p.Name ProductName,c.CategoryName,sz.SizeValue,co.ColorName,bi.Quantity,bi.ReorderLevel,
 CASE WHEN bi.Quantity=0 THEN 'OUT_OF_STOCK' WHEN bi.Quantity<=bi.ReorderLevel THEN 'LOW_STOCK' WHEN bi.Quantity>=bi.ReorderLevel*8 THEN 'OVERSTOCK' ELSE 'IN_STOCK' END StockStatus,
 bi.Quantity*p.CostPrice CostValue,bi.Quantity*p.SellingPrice RetailValue,bi.UpdatedAt LastUpdated,b.BranchID,NULL WarehouseID
FROM branch_inventory bi JOIN branches b ON b.BranchID=bi.BranchID JOIN product_variants pv ON pv.VariantID=bi.VariantID JOIN products p ON p.ProductID=pv.ProductID JOIN categories c ON c.CategoryID=p.CategoryID JOIN sizes sz ON sz.SizeID=pv.SizeID JOIN colors co ON co.ColorID=pv.ColorID
UNION ALL
SELECT 'WAREHOUSE',w.Name,p.ProductID,pv.VariantID,p.SKU,p.Name,c.CategoryName,sz.SizeValue,co.ColorName,wi.Quantity,wi.ReorderLevel,
 CASE WHEN wi.Quantity=0 THEN 'OUT_OF_STOCK' WHEN wi.Quantity<=wi.ReorderLevel THEN 'LOW_STOCK' WHEN wi.Quantity>=wi.ReorderLevel*8 THEN 'OVERSTOCK' ELSE 'IN_STOCK' END,
 wi.Quantity*p.CostPrice,wi.Quantity*p.SellingPrice,wi.UpdatedAt,NULL,w.WarehouseID
FROM warehouse_inventory wi JOIN warehouses w ON w.WarehouseID=wi.WarehouseID JOIN product_variants pv ON pv.VariantID=wi.VariantID JOIN products p ON p.ProductID=pv.ProductID JOIN categories c ON c.CategoryID=p.CategoryID JOIN sizes sz ON sz.SizeID=pv.SizeID JOIN colors co ON co.ColorID=pv.ColorID;
CREATE VIEW v_low_stock AS SELECT * FROM v_current_inventory WHERE StockStatus IN ('LOW_STOCK','OUT_OF_STOCK');
CREATE VIEW v_daily_sales AS SELECT DATE(SaleDate) SaleDay,BranchID,COUNT(*) Transactions,SUM(GrossAmount) GrossSales,SUM(DiscountAmount) Discounts,SUM(NetAmount) Revenue,SUM(CostAmount) COGS,SUM(GrossProfit) GrossProfit FROM sales WHERE Status<>'CANCELLED' GROUP BY DATE(SaleDate),BranchID;
CREATE VIEW v_monthly_sales AS SELECT DATE_FORMAT(SaleDate,'%Y-%m') Month,BranchID,COUNT(*) Transactions,SUM(NetAmount) Revenue,SUM(GrossProfit) GrossProfit FROM sales WHERE Status<>'CANCELLED' GROUP BY DATE_FORMAT(SaleDate,'%Y-%m'),BranchID;
CREATE VIEW v_product_performance AS SELECT p.ProductID,p.SKU,p.Name ProductName,c.CategoryName,SUM(si.Quantity-si.ReturnedQuantity) UnitsSold,SUM(si.LineTotal) Revenue,SUM(si.LineTotal-si.CostAtSale*si.Quantity) GrossProfit FROM sale_items si JOIN sales s ON s.SaleID=si.SaleID JOIN product_variants pv ON pv.VariantID=si.VariantID JOIN products p ON p.ProductID=pv.ProductID JOIN categories c ON c.CategoryID=p.CategoryID WHERE s.Status<>'CANCELLED' GROUP BY p.ProductID,p.SKU,p.Name,c.CategoryName;
CREATE VIEW v_branch_performance AS SELECT b.BranchID,b.Name BranchName,COUNT(s.SaleID) Transactions,COALESCE(SUM(s.NetAmount),0) Revenue,COALESCE(SUM(s.GrossProfit),0) GrossProfit FROM branches b LEFT JOIN sales s ON s.BranchID=b.BranchID AND s.Status<>'CANCELLED' GROUP BY b.BranchID,b.Name;
CREATE VIEW v_cashier_performance AS SELECT u.UserID,u.FullName Cashier,e.BranchID,COUNT(s.SaleID) Transactions,COALESCE(SUM(s.NetAmount),0) Revenue,COALESCE(SUM(s.GrossProfit),0) GrossProfit FROM users u JOIN employees e ON e.UserID=u.UserID LEFT JOIN sales s ON s.CashierUserID=u.UserID AND s.Status<>'CANCELLED' GROUP BY u.UserID,u.FullName,e.BranchID;
CREATE VIEW v_customer_statistics AS SELECT c.CustomerID,c.FullName,COUNT(s.SaleID) PurchaseCount,COALESCE(SUM(s.NetAmount),0) LifetimeSpending,MAX(s.SaleDate) LastPurchaseDate FROM customers c LEFT JOIN sales s ON s.CustomerID=c.CustomerID AND s.Status<>'CANCELLED' GROUP BY c.CustomerID,c.FullName;
CREATE VIEW v_order_statistics AS SELECT DATE(OrderDate) OrderDay,BranchID,Status,COUNT(*) OrderCount,SUM(TotalAmount) OrderValue FROM online_orders GROUP BY DATE(OrderDate),BranchID,Status;
CREATE VIEW v_return_statistics AS SELECT DATE(RequestDate) ReturnDay,BranchID,RequestType,Status,COUNT(*) RequestCount,SUM(RefundAmount) RefundTotal FROM return_requests GROUP BY DATE(RequestDate),BranchID,RequestType,Status;
CREATE VIEW v_monthly_gross_profit AS SELECT DATE_FORMAT(SaleDate,'%Y-%m') Month,BranchID,SUM(NetAmount) Revenue,SUM(CostAmount) COGS,SUM(GrossProfit) GrossProfit FROM sales WHERE Status<>'CANCELLED' GROUP BY DATE_FORMAT(SaleDate,'%Y-%m'),BranchID;
CREATE VIEW v_monthly_expenses AS SELECT DATE_FORMAT(ExpenseDate,'%Y-%m') Month,BranchID,SUM(Amount) Expenses FROM expenses WHERE Status='APPROVED' GROUP BY DATE_FORMAT(ExpenseDate,'%Y-%m'),BranchID;
CREATE VIEW v_monthly_net_profit AS SELECT g.Month,g.BranchID,g.Revenue,g.COGS,g.GrossProfit,COALESCE(e.Expenses,0) Expenses,g.GrossProfit-COALESCE(e.Expenses,0) NetProfit FROM v_monthly_gross_profit g LEFT JOIN v_monthly_expenses e ON e.Month=g.Month AND e.BranchID=g.BranchID;

-- Safe triggers: only assign NEW values; no same-table UPDATE and no circular calls.
DELIMITER $$
CREATE TRIGGER trg_users_before_update BEFORE UPDATE ON users FOR EACH ROW BEGIN SET NEW.UpdatedAt=CURRENT_TIMESTAMP; END$$
CREATE TRIGGER trg_products_before_update BEFORE UPDATE ON products FOR EACH ROW BEGIN SET NEW.UpdatedAt=CURRENT_TIMESTAMP; END$$
DELIMITER ;

-- Required security reference data
INSERT INTO roles(RoleName,Description) VALUES
('OWNER','Full business ownership'),('ADMIN','Authorized administration'),('MANAGER','Assigned branch management'),('CASHIER','Point of sale and own shift'),('WAREHOUSE','Warehouse operations'),('CUSTOMER','Personal shopping account');
INSERT INTO permissions(PermissionCode,Description) VALUES
('VIEW_DASHBOARD','View Dashboard'),
('MANAGE_USERS','Manage Users'),
('MANAGE_ROLES','Manage Roles'),
('MANAGE_PRODUCTS','Manage Products'),
('VIEW_PRODUCT_COST','View Product Cost'),
('MANAGE_INVENTORY','Manage Inventory'),
('CREATE_SALE','Create Sale'),
('CANCEL_SALE','Cancel Sale'),
('PROCESS_RETURN','Process Return'),
('APPROVE_RETURN','Approve Return'),
('VIEW_ALL_BRANCHES','View All Branches'),
('VIEW_BRANCH_SALES','View Branch Sales'),
('MANAGE_CUSTOMERS','Manage Customers'),
('MANAGE_EMPLOYEES','Manage Employees'),
('VIEW_SALARIES','View Salaries'),
('MANAGE_EXPENSES','Manage Expenses'),
('APPROVE_EXPENSES','Approve Expenses'),
('MANAGE_DISCOUNTS','Manage Discounts'),
('APPROVE_STOCK_REQUEST','Approve Stock Request'),
('MANAGE_WAREHOUSE','Manage Warehouse'),
('EXPORT_REPORTS','Export Reports'),
('VIEW_NET_PROFIT','View Net Profit'),
('MANAGE_SETTINGS','Manage Settings'),
('VIEW_AUDIT_LOG','View Audit Log'),
('DATABASE_BACKUP','Database Backup'),
('DATABASE_RESTORE','Database Restore'),
('MANAGE_ORDERS','Manage Orders'),
('MANAGE_SUPPLIERS','Manage Suppliers'),
('MANAGE_PURCHASING','Manage Purchasing'),
('CREATE_DAILY_CLOSING','Create Daily Closing');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='OWNER' AND p.PermissionCode IN ('VIEW_DASHBOARD','MANAGE_USERS','MANAGE_ROLES','MANAGE_PRODUCTS','VIEW_PRODUCT_COST','MANAGE_INVENTORY','CREATE_SALE','CANCEL_SALE','PROCESS_RETURN','APPROVE_RETURN','VIEW_ALL_BRANCHES','VIEW_BRANCH_SALES','MANAGE_CUSTOMERS','MANAGE_EMPLOYEES','VIEW_SALARIES','MANAGE_EXPENSES','APPROVE_EXPENSES','MANAGE_DISCOUNTS','APPROVE_STOCK_REQUEST','MANAGE_WAREHOUSE','EXPORT_REPORTS','VIEW_NET_PROFIT','MANAGE_SETTINGS','VIEW_AUDIT_LOG','DATABASE_BACKUP','DATABASE_RESTORE','MANAGE_ORDERS','MANAGE_SUPPLIERS','MANAGE_PURCHASING','CREATE_DAILY_CLOSING');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='ADMIN' AND p.PermissionCode IN ('VIEW_DASHBOARD','MANAGE_USERS','MANAGE_ROLES','MANAGE_PRODUCTS','VIEW_PRODUCT_COST','MANAGE_INVENTORY','CREATE_SALE','CANCEL_SALE','PROCESS_RETURN','APPROVE_RETURN','VIEW_ALL_BRANCHES','VIEW_BRANCH_SALES','MANAGE_CUSTOMERS','MANAGE_EMPLOYEES','VIEW_SALARIES','MANAGE_EXPENSES','APPROVE_EXPENSES','MANAGE_DISCOUNTS','APPROVE_STOCK_REQUEST','MANAGE_WAREHOUSE','EXPORT_REPORTS','MANAGE_SETTINGS','VIEW_AUDIT_LOG','DATABASE_BACKUP','DATABASE_RESTORE','MANAGE_ORDERS','MANAGE_SUPPLIERS','MANAGE_PURCHASING','CREATE_DAILY_CLOSING');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='MANAGER' AND p.PermissionCode IN ('VIEW_DASHBOARD','MANAGE_PRODUCTS','VIEW_PRODUCT_COST','MANAGE_INVENTORY','CANCEL_SALE','PROCESS_RETURN','APPROVE_RETURN','VIEW_BRANCH_SALES','MANAGE_CUSTOMERS','MANAGE_EMPLOYEES','VIEW_SALARIES','MANAGE_EXPENSES','APPROVE_EXPENSES','MANAGE_DISCOUNTS','APPROVE_STOCK_REQUEST','EXPORT_REPORTS','MANAGE_ORDERS','CREATE_DAILY_CLOSING');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='CASHIER' AND p.PermissionCode IN ('VIEW_DASHBOARD','CREATE_SALE','PROCESS_RETURN','VIEW_BRANCH_SALES','MANAGE_CUSTOMERS','CREATE_DAILY_CLOSING');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='WAREHOUSE' AND p.PermissionCode IN ('VIEW_DASHBOARD','MANAGE_PRODUCTS','VIEW_PRODUCT_COST','MANAGE_INVENTORY','APPROVE_STOCK_REQUEST','MANAGE_WAREHOUSE','EXPORT_REPORTS','MANAGE_SUPPLIERS','MANAGE_PURCHASING');
INSERT INTO role_permissions(RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM roles r CROSS JOIN permissions p WHERE r.RoleName='CUSTOMER' AND p.PermissionCode IN ('VIEW_DASHBOARD','PROCESS_RETURN','MANAGE_ORDERS');

SET FOREIGN_KEY_CHECKS=1;
